version: '3'
services: 
  db:
    image: mongo:3.4
  backend:
    image: node:10.16.3
    volumes: 
      - ./:/sky
    ports:
      - 3000:3000
    command: bash -c "cd /sky && npm install -g nodemon && npm i && npm start"
